"""
Batch candidate generation from JSON plan with checkpointing.

This is a self-contained script for large-scale structure generation (N > 20) 
using MCP tools. It supports both stdio (local) and SSE/HTTP (remote) connections,
with automatic checkpoint/resume capability.

Architecture:
    - Client-side: Pure Python (only requires matclaw_sdk)
    - Structure format: CIF (standard crystallographic format) for all I/O
    - Server-side: MCP tools handled transparently by matclaw_sdk

Dependencies:
    pip install -e /path/to/MatClaw/sdk/

Usage:
    # Run directly (connection configured via sdk/config.yaml)
    python batch_generation.py
    
    # Resume automatically (script tracks progress in the plan file)
    python batch_generation.py

The script tracks progress directly in the plan file (adds 'status' field to each 
candidate), allowing automatic resume if interrupted. Completed structures are saved 
as CIF files in the output directory.

# =============================================================================
# CUSTOMIZATION GUIDE FOR PROJECT-SPECIFIC SCRIPTS
# =============================================================================
# This script is a REFERENCE TEMPLATE demonstrating MCP integration patterns.
# DO NOT EDIT THIS FILE DIRECTLY for your project.
#
# Instead, copy relevant patterns and adapt them:
#
# 1. TOOL SELECTION (line ~340)
#    - Default: Reads 'tool' field from candidate or batch
#    - Customize: Add tool name validation, default tools per batch type
#
# 2. BASE STRUCTURE RESOLUTION (line ~475-510)
#    - Default: Tries multiple sources in priority order:
#      * tool_parameters.base_mp_id / base_cod_id / material_id
#      * candidate.base_mp_id / base_cod_id / material_id
#      * candidate.base_composition (formula to search MP, fallback COD)
#      * batch.base_structure_query.mp_id / cod_id / formula
#    - COD support: pass base_cod_id for direct COD lookups, or just a formula
#      and the generator will try MP first, then COD
#    - Customize: Add support for local CIF files, prototype generation, etc.
#
# 3. TOOL PARAMETERS (line ~325)
#    - Default: Passes tool_parameters dict directly to MCP tool
#    - Customize: Add parameter validation, transform params, inject defaults
#
# 4. WORKFLOW (line ~530)
#    - Default: Single tool call per candidate
#    - Customize: Add multi-step pipelines, post-processing, validation
#
# =============================================================================
"""

import asyncio
import argparse
import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional

from matclaw_sdk import async_call_tool


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# ============================================================================
# Utility Functions
# ============================================================================




def save_plan(plan_file: Path, plan: dict):
    """Save plan to file with atomic write."""
    # Write to temporary file first
    temp_file = plan_file.with_suffix('.tmp')
    with open(temp_file, 'w') as f:
        json.dump(plan, f, indent=2)
    
    # Atomic rename (POSIX) / replace (Windows)
    temp_file.replace(plan_file)





# ============================================================================
# Batch Generator Class
# ============================================================================


class BatchGenerator:
    """
    Batch structure generator with progress tracking and error handling.
    """
    
    def __init__(self, plan_file: Path, output_dir: Path):
        self.plan_file = plan_file
        self.output_dir = output_dir
        
        # State
        self.plan = None
        self.base_cache: Dict[str, dict] = {}  # Cache for base structures (material_id -> CIF)
        self.formula_to_id_cache: Dict[str, str] = {}  # Cache for formula -> material_id lookups
    
    def load_plan(self):
        """Load generation plan from JSON."""
        logger.info(f"Loading plan from {self.plan_file}")
        with open(self.plan_file) as f:
            self.plan = json.load(f)
        
        # Initialize status field for candidates if not present
        for batch in self.plan['batches']:
            for candidate in batch['candidates']:
                if 'status' not in candidate:
                    candidate['status'] = 'pending'
        
        total = self.plan['metadata']['total_planned']
        logger.info(f"Plan loaded: {total} candidates across {len(self.plan['batches'])} batches")
        
        # Count current progress
        completed = sum(1 for batch in self.plan['batches'] 
                       for c in batch['candidates'] if c.get('status') == 'completed')
        failed = sum(1 for batch in self.plan['batches'] 
                    for c in batch['candidates'] if c.get('status') == 'failed')
        
        if completed + failed > 0:
            logger.info(f"Resuming from previous run: {completed} completed, {failed} failed")
        else:
            logger.info("Starting fresh (no previous progress found)")
    
    def save_plan(self):
        """Save plan with updated progress."""
        self.plan['metadata']['last_updated'] = datetime.now().isoformat()
        save_plan(self.plan_file, self.plan)
    
    async def get_base_structure(self, material_id: str) -> Optional[str]:
        """
        Get base structure from Materials Project or COD with caching.

        Supports both MP IDs (e.g., "mp-4591") and COD IDs (e.g., "cod-1522217").
        If the ID starts with "mp-", queries MP. If it starts with "cod-",
        queries COD. Otherwise, treats as an MP ID.

        Args:
            material_id: Material ID (e.g., "mp-4591" or "cod-1522217")

        Returns:
            CIF string or None if error
        """
        # Check cache first
        if material_id in self.base_cache:
            logger.debug(f"Using cached base structure {material_id}")
            return self.base_cache[material_id]

        # Route to the right database based on ID prefix
        is_cod = material_id.lower().startswith("cod-")
        db_name = "COD" if is_cod else "Materials Project"

        if is_cod:
            cod_id = material_id.replace("cod-", "")
            try:
                cod_id_int = int(cod_id)
            except ValueError:
                logger.error(f"[ERROR] Invalid COD ID: {material_id}")
                return None

            logger.info(f"Fetching base structure {material_id} from COD...")
            try:
                result = await async_call_tool(
                    "cod_search_structures",
                    cod_ids=[cod_id_int],
                    include_cifs=True,
                    max_results=1
                )

                if result and result.get('count', 0) > 0:
                    structure_data = result['structures'][0]
                    cif_string = structure_data.get('cif')
                    if cif_string:
                        self.base_cache[material_id] = cif_string
                        logger.info(f"[OK] Fetched {material_id} from COD "
                                    f"({structure_data.get('formula', '?')})")
                        return cif_string
                    else:
                        logger.error(f"[ERROR] No CIF data in COD result for {material_id}")
                else:
                    logger.error(f"[ERROR] COD ID {material_id} not found")
                return None

            except Exception as e:
                import traceback
                logger.error(f"[ERROR] Error fetching {material_id} from COD: {e}")
                logger.error(f"Traceback: {traceback.format_exc()}")
                return None

        # MP path (existing logic)
        logger.info(f"Fetching base structure {material_id} from Materials Project...")
        try:
            result = await async_call_tool(
                "mp_get_material_properties",
                material_ids=[material_id]
            )

            # Check for errors/warnings from MP tool
            if 'error' in result:
                logger.error(f"[ERROR] MP tool error: {result['error']}")
            if 'warnings' in result:
                for warning in result['warnings']:
                    logger.warning(f"[WARNING] MP tool warning: {warning}")
            
            # Extract CIF from MP response (server returns CIF format directly)
            if 'properties' in result and len(result['properties']) > 0:
                material_data = result['properties'][0]
                if material_data.get('material_id') == material_id and 'structure' in material_data:
                    structure_data = material_data['structure']
                    cif_string = structure_data.get('cif')
                    
                    if cif_string:
                        self.base_cache[material_id] = cif_string
                        num_sites = structure_data.get('num_sites', 'unknown')
                        spacegroup = structure_data.get('space_group_symbol', 'unknown')
                        logger.info(f"[OK] Fetched {material_id} ({spacegroup}, {num_sites} sites)")
                        return self.base_cache[material_id]
                    else:
                        logger.error(f"[ERROR] No CIF data in structure for {material_id}")
                else:
                    logger.error(f"[ERROR] Invalid structure data for {material_id}")
            else:
                logger.error(f"[ERROR] No properties data for {material_id}")
            
            return None
                
        except Exception as e:
            import traceback
            logger.error(f"[ERROR] Error fetching {material_id}: {e}")
            logger.error(f"Traceback: {traceback.format_exc()}")
            return None
    
    async def generate_structure(self, candidate: dict, base_cif: str, batch: dict) -> Optional[str]:
        """
        Generate structure using matclaw_sdk tool (dynamic tool selection).

        This method demonstrates FLEXIBLE tool calling:
        - Reads tool name from candidate or batch (not hardcoded)
        - Passes tool_parameters directly without assumptions
        - Injects base structure automatically if not in params

        Args:
            candidate: Candidate dict from plan
            base_cif: Base structure as CIF string
            batch: Parent batch dict

        Returns:
            CIF string or None if error
        """
        # DYNAMIC TOOL SELECTION: Read from candidate, fall back to batch default
        tool_name = candidate.get('tool') or batch.get('tool')
        if not tool_name:
            raise ValueError(f"No tool specified for candidate {candidate.get('id')}")
        
        tool_params = candidate.get('tool_parameters', {}).copy()
        
        try:
            # AUTOMATIC BASE STRUCTURE INJECTION
            # Most structure generation tools expect input_structures parameter
            # If not provided, inject the base structure automatically
            if 'input_structures' not in tool_params and base_cif:
                tool_params['input_structures'] = [base_cif]
            
            # FORCE CIF OUTPUT: Preserve disorder/partial occupancy information
            # (Some tools support output_format parameter)
            if 'output_format' not in tool_params:
                tool_params['output_format'] = 'cif'
            
            logger.debug(f"  Calling {tool_name} with params: {list(tool_params.keys())}")
            
            # Call MCP tool dynamically
            result = await async_call_tool(tool_name, **tool_params)

            # Check for tool-level errors
            if isinstance(result, dict) and 'success' in result and not result['success']:
                logger.error(f"[ERROR] Tool error: {result.get('error', 'Unknown error')}")
                return None
            
            if result and 'structures' in result and len(result['structures']) > 0:
                return result['structures'][0]
            else:
                logger.error(f"[ERROR] No structure returned. Data: {result}")
                return None
                
        except Exception as e:
            logger.error(f"[ERROR] Error generating structure: {e}")
            return None
    
    async def find_material_id(self, formula: str) -> Optional[str]:
        """
        Find structure ID for a given formula.

        Searches MP first (for rich property data), then falls back to COD
        if not found. Returns "mp-XXXX" or "cod-XXXX" format IDs.

        Args:
            formula: Chemical formula (e.g., "SrNb2O6")

        Returns:
            Material ID (e.g., "mp-4591" or "cod-1522217") or None if not found
        """
        # Check cache first
        if formula in self.formula_to_id_cache:
            logger.debug(f"  Using cached material ID for {formula}")
            return self.formula_to_id_cache[formula]
        
        # Try MP first
        try:
            logger.info(f"  Searching Materials Project for {formula}...")
            result = await async_call_tool(
                "mp_search_materials",
                formula=formula,
                num_results=5
            )

            if not result or 'materials' not in result:
                logger.error(f"  Error parsing mp_search_materials response. Check tool response format.")
                # Fall through to COD
            elif len(result['materials']) > 0:
                # Prefer stable materials (energy_above_hull = 0)
                stable_materials = [
                    m for m in result['materials'] 
                    if m.get('energy_above_hull', float('inf')) == 0
                ]
                
                if stable_materials:
                    material_id = stable_materials[0]['material_id']
                    logger.info(f"  Found stable material on MP: {material_id}")
                else:
                    # No stable materials, take the first one
                    material_id = result['materials'][0]['material_id']
                    logger.warning(f"  No stable materials found on MP, using {material_id}")
                
                # Cache the result
                self.formula_to_id_cache[formula] = material_id
                return material_id
            else:
                logger.warning(f"  No materials found on MP for {formula}")
        except Exception as e:
            logger.warning(f"  MP search error for {formula}: {e}")
        
        # Fall back to COD
        try:
            logger.info(f"  Searching COD for {formula}...")
            cod_result = await async_call_tool(
                "cod_search_structures",
                formula=formula,
                max_results=5,
                include_cifs=False
            )

            if cod_result and cod_result.get('count', 0) > 0:
                # Use the first matching COD entry
                cod_id = cod_result['structures'][0]['cod_id']
                material_id = f"cod-{cod_id}"
                logger.info(f"  Found structure on COD: {material_id}")
                self.formula_to_id_cache[formula] = material_id
                return material_id
            else:
                logger.error(f"  No structures found on COD for {formula}")
                
        except Exception as e:
            logger.error(f"  COD search error for {formula}: {e}")
        
        return None
    
    def save_structure(self, candidate_id: str, formula: str, structure_data: str) -> Path:
        """
        Save structure to CIF file.
        
        Args:
            candidate_id: Candidate ID (e.g., "CAND-001")
            formula: Chemical formula
            structure_data: CIF string from disorder generator
            
        Returns:
            Path to saved CIF file
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        filename = f"{candidate_id}_{formula}.cif"
        cif_path = self.output_dir / filename
        
        # All tools return CIF strings - no conversion needed
        if not isinstance(structure_data, str):
            raise ValueError(f"Expected CIF string, got {type(structure_data)}")
        
        cif_path.write_text(structure_data)
        return cif_path
    
    async def process_candidate(self, candidate: dict, batch: dict) -> bool:
        """
        Process a single candidate with flexible base structure resolution.

        CUSTOMIZATION POINT: This method demonstrates the complete workflow.
        Adapt the base structure resolution logic for your specific needs.

        Args:
            candidate: Candidate dict from plan
            batch: Parent batch dict

        Returns:
            True if successful, False otherwise
        """
        cand_id = candidate['id']
        formula = candidate['formula']
        status = candidate.get('status', 'pending')
        
        # Skip if already completed
        if status == 'completed':
            logger.info(f"{cand_id}: Already completed, skipping")
            return True
        
        # Show retry message if previously failed
        if status == 'failed':
            logger.info(f"{cand_id}: Previously failed, retrying...")
        
        logger.info(f"{cand_id}: Processing {formula}...")
        
        try:
            # =========================================================
            # FLEXIBLE BASE STRUCTURE RESOLUTION
            # Tries multiple sources in priority order:
            # 1. Direct MP/COD ID in tool_parameters
            # 2. Direct MP/COD ID in candidate
            # 3. Formula in candidate (search MP, fallback COD)
            # 4. Formula in batch query (search MP, fallback COD)
            # 5. Direct MP/COD ID in batch query
            # =========================================================
            
            base_cif = None
            base_id = None
            
            # Priority 1: Direct MP or COD ID in tool_parameters
            tool_params = candidate.get('tool_parameters', {})
            for id_key in ('base_mp_id', 'base_cod_id', 'material_id'):
                if id_key in tool_params:
                    base_id = tool_params[id_key]
                    logger.debug(f"  Using {id_key} from tool_parameters: {base_id}")
                    base_cif = await self.get_base_structure(base_id)
                    if base_cif:
                        break
            
            # Priority 2: Direct MP or COD ID at candidate level
            if not base_cif:
                for id_key in ('base_mp_id', 'base_cod_id', 'material_id'):
                    if id_key in candidate:
                        base_id = candidate[id_key]
                        logger.debug(f"  Using {id_key} from candidate: {base_id}")
                        base_cif = await self.get_base_structure(base_id)
                        if base_cif:
                            break
            
            # Priority 3: Formula in candidate (search MP)
            elif 'base_composition' in candidate:
                base_formula = candidate['base_composition']
                logger.debug(f"  Searching MP for base_composition: {base_formula}")
                base_id = await self.find_material_id(base_formula)
                if base_id:
                    base_cif = await self.get_base_structure(base_id)
            
            # Priority 4 & 5: Batch-level defaults
            elif 'base_structure_query' in batch:
                base_query = batch['base_structure_query']
            
                # Try direct MP ID or COD ID first
                if 'mp_id' in base_query:
                    base_id = base_query['mp_id']
                    logger.debug(f"  Using mp_id from batch query: {base_id}")
                    base_cif = await self.get_base_structure(base_id)
                elif 'cod_id' in base_query:
                    base_id = f"cod-{base_query['cod_id']}"
                    logger.debug(f"  Using cod_id from batch query: {base_id}")
                    base_cif = await self.get_base_structure(base_id)
                
                # Fall back to formula search
                elif 'formula' in base_query:
                    base_formula = base_query['formula']
                    logger.debug(f"  Searching MP for batch formula: {base_formula}")
                    base_id = await self.find_material_id(base_formula)
                    if base_id:
                        base_cif = await self.get_base_structure(base_id)
            
            # Validation: Ensure we got a base structure
            if not base_cif:
                raise ValueError(
                    f"Could not resolve base structure. Tried: "
                    f"tool_parameters.base_mp_id/base_cod_id, candidate.base_mp_id/base_cod_id, "
                    f"candidate.base_composition, batch.base_structure_query"
                )
            
            # Generate structure (with dynamic tool selection)
            cif_content = await self.generate_structure(candidate, base_cif, batch)
            if not cif_content:
                raise ValueError("Structure generation failed")
            
            # Save CIF
            cif_path = self.save_structure(cand_id, formula, cif_content)
            logger.info(f"{cand_id}: [OK] Saved to {cif_path}")
            
            # Update candidate status
            candidate['status'] = 'completed'
            candidate['completed_at'] = datetime.now().isoformat()
            candidate['output_file'] = str(cif_path)
            if 'error' in candidate:
                del candidate['error']
            
            self.save_plan()
            
            return True
            
        except Exception as e:
            logger.error(f"{cand_id}: [ERROR] Error - {e}")
            
            # Update candidate status
            candidate['status'] = 'failed'
            candidate['error'] = str(e)
            candidate['failed_at'] = datetime.now().isoformat()
            
            self.save_plan()
            
            return False
    
    async def run(self):
        """Run batch generation with progress tracking."""
        self.load_plan()
        self.output_dir.mkdir(parents=True, exist_ok=True)

        total_candidates = self.plan['metadata']['total_planned']
        processed = 0

        for batch in self.plan['batches']:
            batch_id = batch['batch_id']
            logger.info(f"\n{'='*60}")
            logger.info(f"Batch {batch_id}: {batch['description']}")
            logger.info(f"{'='*60}")

            for candidate in batch['candidates']:
                await self.process_candidate(candidate, batch)
                processed += 1

                completed = sum(1 for b in self.plan['batches']
                               for c in b['candidates'] if c.get('status') == 'completed')
                failed = sum(1 for b in self.plan['batches']
                            for c in b['candidates'] if c.get('status') == 'failed')
                logger.info(f"Progress: {processed}/{total_candidates} processed "
                          f"({completed} completed, {failed} failed)")

        completed = sum(1 for b in self.plan['batches']
                       for c in b['candidates'] if c.get('status') == 'completed')
        failed = sum(1 for b in self.plan['batches']
                    for c in b['candidates'] if c.get('status') == 'failed')
        logger.info(f"\n{'='*60}")
        logger.info(f"FINAL SUMMARY")
        logger.info(f"{'='*60}")
        logger.info(f"Total candidates: {total_candidates}")
        logger.info(f"Completed: {completed}")
        logger.info(f"Failed: {failed}")
        logger.info(f"Success rate: {completed/total_candidates*100:.1f}%")


async def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Batch candidate generation with progress tracking"
    )
    parser.add_argument(
        '--plan',
        type=Path,
        default=Path('generation_candidates.json'),
        help='Path to candidate generation file (tracks progress in-place)'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=Path('candidate-generation'),
        help='Output directory for CIF files'
    )
    
    args = parser.parse_args()
    
    # Create generator
    generator = BatchGenerator(
        plan_file=args.plan,
        output_dir=args.output_dir
    )
    
    # Run
    await generator.run()


if __name__ == "__main__":
    asyncio.run(main())
