"""
Batch candidate screening with hierarchical property retrieval and checkpointing.

This is a self-contained reference script for large-scale screening (N > 20)
using MCP tools. Demonstrates:
    - Hierarchical property retrieval (Materials Project → ASE cache → ML predictions)
    - Multi-phase screening (validation → properties → criteria → ranking)
    - Checkpoint/resume capability
    - Both stdio (local) and SSE (remote) MCP connections

Architecture:
    - Client-side: Pure Python (only requires matclaw_sdk)
    - Structure format: CIF (standard crystallographic format) for all I/O
    - Server-side: MCP tools handled transparently by matclaw_sdk

Dependencies:
    pip install -e /path/to/MatClaw/sdk/

Usage:
    # Run directly (connection configured via sdk/config.yaml)
    python batch_screening_example.py

    # Resume automatically (script tracks progress in screening_results.json)
    python batch_screening_example.py

The script tracks progress in screening_results.json, allowing automatic resume
if interrupted. Results include detailed properties, screening outcomes, and rankings.

# =============================================================================
# CUSTOMIZATION GUIDE FOR PROJECT-SPECIFIC SCRIPTS
# =============================================================================
# This script is a REFERENCE TEMPLATE demonstrating MCP screening patterns.
# DO NOT EDIT THIS FILE DIRECTLY for your project.
#
# Instead, copy and adapt these patterns:
#
# 1. SCREENING CRITERIA (line ~400)
#    - Default: Band gap, formation energy, energy above hull
#    - Customize: Add application-specific filters (magnetic properties, etc.)
#
# 2. HIERARCHICAL RETRIEVAL (line ~450)
#    - Default: MP → ASE → ML (3-tier)
#    - Customize: Add/remove tiers, change fallback logic, add local databases
#
# 3. SCORING FUNCTION (line ~550)
#    - Default: Multi-objective weighted score
#    - Customize: Change weights, add objectives, apply domain-specific heuristics
#
# 4. RANKING TIERS (line ~600)
#    - Default: TOP/SECOND/THIRD based on scores + data confidence
#    - Customize: Add recommendation logic specific to your application
#
# =============================================================================
"""

import asyncio
import argparse
import json
import logging
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, List

from matclaw_sdk import async_call_tool


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# ============================================================================
# Utility Functions
# ============================================================================




def save_results(results_file: Path, results: dict):
    """Save results to file with atomic write."""
    # Write to temporary file first
    temp_file = results_file.with_suffix('.tmp')
    with open(temp_file, 'w') as f:
        json.dump(results, f, indent=2)
    
    # Atomic rename (POSIX) / replace (Windows)
    temp_file.replace(results_file)


# ============================================================================
# Batch Screener Class
# ============================================================================


class BatchScreener:
    """
    Batch candidate screener with hierarchical property retrieval and checkpointing.
    
    Workflow:
        Phase 1: Structure validation (structure_validator, composition_analyzer)
        Phase 2: Property retrieval (hierarchical: MP → ASE cache → ML)
        Phase 3: Screening criteria (user-defined filters)
        Phase 4: Scoring and ranking
    """
    
    def __init__(self, 
                 candidates_dir: Path, 
                 results_file: Path,
                 ase_db_path: Optional[Path] = None,
                 criteria: Optional[Dict] = None):
        self.candidates_dir = Path(candidates_dir)
        self.results_file = results_file
        self.ase_db_path = ase_db_path
        
        # Screening criteria (CUSTOMIZATION POINT)
        self.criteria = criteria or {
            "band_gap_min": 3.0,
            "band_gap_max": 6.0,
            "energy_above_hull_max": 0.5,  # eV/atom
            "formation_energy_max": 0.0,  # eV/atom
        }
        
        # Results state
        self.results = {
            "metadata": {
                "screening_date": datetime.now().isoformat(),
                "total_candidates": 0,
                "screening_time_seconds": 0
            },
            "summary_statistics": {
                "validated": 0,
                "validation_failed": 0,
                "with_properties": 0,
                "properties_failed": 0,
                "passed_filters": 0,
                "screening_failed": 0,
                "ranked": 0
            },
            "data_sources": {
                "materials_project": 0,
                "ase_cached": 0,
                "ml_calculated": 0
            },
            "candidates": []
        }
    
    def load_candidates(self) -> List[Dict]:
        """Load CIF files from candidates directory."""
        cif_files = list(self.candidates_dir.glob("*.cif"))
        logger.info(f"Found {len(cif_files)} CIF files in {self.candidates_dir}")
        
        candidates = []
        for cif_file in sorted(cif_files):
            with open(cif_file, 'r') as f:
                cif_string = f.read()
            
            # Extract candidate ID from filename (e.g., CAND-001_Formula.cif)
            filename = cif_file.stem
            parts = filename.split('_')
            cand_id = parts[0] if parts else filename
            
            candidates.append({
                "id": cand_id,
                "filename": cif_file.name,
                "cif_string": cif_string,
                "status": "pending",
                "properties": {},
                "screening_result": {
                    "passed": None,
                    "failed_criteria": [],
                    "scores": {},
                    "rank": None
                }
            })
        
        self.results["metadata"]["total_candidates"] = len(candidates)
        return candidates
    
    def load_checkpoint(self) -> Optional[List[Dict]]:
        """Load existing results to resume from checkpoint."""
        if not self.results_file.exists():
            logger.info("No checkpoint found, starting fresh")
            return None
        
        try:
            with open(self.results_file) as f:
                self.results = json.load(f)
            
            pending = sum(1 for c in self.results["candidates"] if c.get("status") == "pending")
            completed = sum(1 for c in self.results["candidates"] 
                          if c.get("status") in ["passed", "screening_failed", "validation_failed", "properties_failed"])
            
            if pending > 0:
                logger.info(f"Resuming from checkpoint: {completed} completed, {pending} pending")
                return self.results["candidates"]
            else:
                logger.info("All candidates already processed")
                return self.results["candidates"]
                
        except Exception as e:
            logger.warning(f"Could not load checkpoint: {e}")
            return None
    
    def save_checkpoint(self):
        """Save current results to JSON file."""
        self.results["metadata"]["last_updated"] = datetime.now().isoformat()
        save_results(self.results_file, self.results)
    
    async def validate_structure(self, candidate: Dict) -> bool:
        """
        Phase 1: Validate structure integrity.

        CUSTOMIZATION POINT: Add additional validation checks.
        """
        try:
            result = await async_call_tool(
                "structure_validator",
                input_structure=candidate["cif_string"],
                check_overlaps=True,
                overlap_tolerance=0.5,
                check_bonds=True,
                check_composition=True
            )
            if result["is_valid"]:
                candidate["properties"]["validity"] = result
                candidate["properties"]["formula"] = result["formula"]
                self.results["summary_statistics"]["validated"] += 1
                logger.info(f"  {candidate['id']}: Structure VALID ({result['formula']})")
                return True
            else:
                candidate["status"] = "validation_failed"
                candidate["screening_result"]["rejection_reason"] = "; ".join(result["issues"])
                self.results["summary_statistics"]["validation_failed"] += 1
                logger.warning(f"  {candidate['id']}: Structure INVALID - {result['issues']}")
                return False
                
        except Exception as e:
            candidate["status"] = "validation_failed"
            candidate["screening_result"]["rejection_reason"] = f"Validation error: {str(e)}"
            self.results["summary_statistics"]["validation_failed"] += 1
            logger.error(f"  {candidate['id']}: Validation exception - {e}")
            return False
    
    async def retrieve_properties_hierarchical(self, candidate: Dict) -> bool:
        """
        Phase 2: Hierarchical property retrieval (MP → ASE → ML).

        CUSTOMIZATION POINT: Modify retrieval hierarchy for your data sources.

        Returns:
            True if properties successfully retrieved, False otherwise
        """
        formula = candidate["properties"]["formula"]

        # Clean formula for base structure search (remove dopants)
        base_formula = self._clean_formula_for_search(formula)

        logger.info(f"  {candidate['id']}: Retrieving properties for {formula} (base: {base_formula})")

        # Try Materials Project first (highest confidence)
        if await self._try_materials_project(candidate, base_formula):
            return True

        # Try ASE cache second (medium confidence)
        if self.ase_db_path and await self._try_ase_cache(candidate, formula):
            return True

        # Fall back to ML predictions (lower confidence, requires DFT verification)
        return await self._run_ml_predictions(candidate)
    
    def _clean_formula_for_search(self, formula: str) -> str:
        """Remove dopants and normalize formula for database search."""
        # Remove common dopant elements
        cleaned = formula
        for dopant in ["Sm", "Eu", "Ce", "Tb", "Dy"]:
            cleaned = cleaned.replace(dopant, "")
        
        # Remove fractional occupancies
        cleaned = re.sub(r'\d+\.\d+', '', cleaned)
        cleaned = re.sub(r'\.', '', cleaned)
        cleaned = re.sub(r'\s+', '', cleaned)
        
        return cleaned
    
    async def _try_materials_project(self, candidate: Dict, formula: str) -> bool:
        """Try to retrieve properties from Materials Project."""
        try:
            # Search for material
            search_result = await async_call_tool(
                "mp_search_materials",
                formula=formula,
                is_stable=None
            )
            if search_result.get("count", 0) == 0:
                logger.info(f"    {candidate['id']}: Not found in Materials Project")
                return False
            
            # Get most stable material
            mp_id = search_result["materials"][0]["material_id"]
            logger.info(f"    {candidate['id']}: Found in MP as {mp_id}")
            
            # Retrieve detailed properties
            props = await async_call_tool(
                "mp_get_material_properties",
                material_ids=[mp_id],
                properties=["formation_energy_per_atom", "band_gap", "energy_above_hull",
                            "symmetry", "density"]
            )

            if props.get("count", 0) > 0:
                mp_data = props["properties"][0]
                candidate["properties"].update({
                    "source": "Materials_Project",
                    "mp_id": mp_id,
                    "formation_energy_per_atom": mp_data.get("formation_energy_per_atom"),
                    "band_gap": mp_data.get("band_gap"),
                    "energy_above_hull": mp_data.get("energy_above_hull"),
                    "confidence": 1.0
                })
                self.results["data_sources"]["materials_project"] += 1
                self.results["summary_statistics"]["with_properties"] += 1
                logger.info(f"    {candidate['id']}: Retrieved MP properties - Eg={mp_data.get('band_gap')} eV, "
                          f"Ehull={mp_data.get('energy_above_hull')} eV/atom")
                return True
                
        except Exception as e:
            logger.warning(f"    {candidate['id']}: MP retrieval failed - {e}")
        
        return False
    
    async def _try_ase_cache(self, candidate: Dict, formula: str) -> bool:
        """Try to retrieve properties from ASE database cache."""
        try:
            result = await async_call_tool(
                "ase_query",
                db_path=str(self.ase_db_path),
                formula=formula
            )
            if result.get("count", 0) > 0:
                # Use most recent entry
                entry = result["results"][0]
                candidate["properties"].update({
                    "source": "ASE_Cache",
                    "formation_energy_per_atom": entry.get("formation_energy_per_atom"),
                    "band_gap": entry.get("band_gap"),
                    "energy_above_hull": entry.get("energy_above_hull"),
                    "confidence": 0.85
                })
                self.results["data_sources"]["ase_cached"] += 1
                self.results["summary_statistics"]["with_properties"] += 1
                logger.info(f"    {candidate['id']}: Retrieved from ASE cache")
                return True
                
        except Exception as e:
            logger.warning(f"    {candidate['id']}: ASE cache retrieval failed - {e}")
        
        return False
    
    async def _run_ml_predictions(self, candidate: Dict) -> bool:
        """Run ML predictions using MatGL."""
        try:
            logger.info(f"    {candidate['id']}: Running ML predictions...")

            # Step 1: Relax structure
            relaxed = await async_call_tool(
                "matgl_relax_structure",
                input_structure=candidate["cif_string"],
                fmax=0.1,
                steps=500,
                optimizer="FIRE"
            )
            if not relaxed.get("converged", False):
                raise Exception("Relaxation did not converge")

            relaxed_structure = relaxed["final_structure"]

            # Save relaxed structure (CRITICAL: preserve for DFT validation)
            candidate["relaxed_structure_cif"] = relaxed_structure

            # Write relaxed structure to individual CIF file for direct DFT input
            relaxed_dir = Path("relaxed_structures")
            relaxed_dir.mkdir(exist_ok=True)
            with open(relaxed_dir / f"{candidate['id']}_relaxed.cif", "w") as f:
                f.write(relaxed_structure)

            # Step 2: Predict formation energy
            eform = await async_call_tool(
                "matgl_predict_eform",
                input_structure=relaxed_structure,
                model="MEGNet-Eform-MP-2018.6.1"
            )

            # Step 3: Predict band gap
            bandgap = await async_call_tool(
                "matgl_predict_bandgap",
                input_structure=relaxed_structure
            )

            candidate["properties"].update({
                "source": "ML_MatGL",
                "formation_energy_per_atom": eform.get("formation_energy_per_atom"),
                "band_gap": bandgap.get("band_gap"),
                "energy_above_hull": None,  # Not available from ML
                "relaxed": True,
                "confidence": 0.70,
                "requires_dft_verification": True
            })

            self.results["data_sources"]["ml_calculated"] += 1
            self.results["summary_statistics"]["with_properties"] += 1

            logger.info(f"    {candidate['id']}: ML predictions - "
                       f"Eform={eform.get('formation_energy_per_atom', 'N/A')} eV/atom, "
                       f"Eg={bandgap.get('band_gap', 'N/A')} eV")
            return True
            
        except Exception as e:
            candidate["status"] = "properties_failed"
            candidate["screening_result"]["rejection_reason"] = f"ML prediction failed: {str(e)}"
            self.results["summary_statistics"]["properties_failed"] += 1
            logger.error(f"    {candidate['id']}: ML prediction failed - {e}")
            return False
    
    def apply_screening_criteria(self, candidate: Dict) -> bool:
        """
        Phase 3: Apply screening criteria.
        
        CUSTOMIZATION POINT: Modify criteria for your application.
        
        Returns:
            True if candidate passes all criteria, False otherwise
        """
        props = candidate["properties"]
        failed_criteria = []
        
        # Check band gap
        band_gap = props.get("band_gap")
        if band_gap is None:
            failed_criteria.append("band_gap_missing")
        elif band_gap < self.criteria["band_gap_min"]:
            failed_criteria.append(f"band_gap_too_low ({band_gap:.2f} < {self.criteria['band_gap_min']})")
        elif band_gap > self.criteria["band_gap_max"]:
            failed_criteria.append(f"band_gap_too_high ({band_gap:.2f} > {self.criteria['band_gap_max']})")
        
        # Check energy above hull (if available)
        energy_above_hull = props.get("energy_above_hull")
        if energy_above_hull is not None and energy_above_hull > self.criteria["energy_above_hull_max"]:
            failed_criteria.append(f"energy_above_hull_too_high ({energy_above_hull:.3f} > {self.criteria['energy_above_hull_max']})")
        
        # Check formation energy
        formation_energy = props.get("formation_energy_per_atom")
        if formation_energy is None:
            failed_criteria.append("formation_energy_missing")
        elif formation_energy > self.criteria["formation_energy_max"]:
            failed_criteria.append(f"formation_energy_positive ({formation_energy:.3f} > {self.criteria['formation_energy_max']})")
        
        candidate["screening_result"]["failed_criteria"] = failed_criteria
        
        if failed_criteria:
            candidate["status"] = "screening_failed"
            candidate["screening_result"]["passed"] = False
            self.results["summary_statistics"]["screening_failed"] += 1
            logger.info(f"  {candidate['id']}: FAILED screening - {failed_criteria}")
            return False
        else:
            candidate["status"] = "passed"
            candidate["screening_result"]["passed"] = True
            self.results["summary_statistics"]["passed_filters"] += 1
            logger.info(f"  {candidate['id']}: PASSED screening")
            return True
    
    def calculate_scores(self, candidate: Dict):
        """
        Calculate multi-objective scores for ranking.
        
        CUSTOMIZATION POINT: Modify scoring function for your application.
        """
        props = candidate["properties"]
        scores = {}
        
        # Score 1: Band gap (simple distance from optimal, can customize)
        band_gap = props.get("band_gap", 0)
        optimal_gap = (self.criteria["band_gap_min"] + self.criteria["band_gap_max"]) / 2
        gap_deviation = abs(band_gap - optimal_gap)
        scores["band_gap_score"] = max(0, 1.0 - gap_deviation / optimal_gap)
        
        # Score 2: Thermodynamic stability
        energy_above_hull = props.get("energy_above_hull")
        if energy_above_hull is not None:
            scores["stability_score"] = max(0, 1.0 - energy_above_hull / self.criteria["energy_above_hull_max"])
        else:
            scores["stability_score"] = 0.5  # Unknown, assume moderate
        
        # Score 3: Formation energy (more negative = better)
        formation_energy = props.get("formation_energy_per_atom", 0)
        scores["formation_energy_score"] = min(1.0, max(0, -formation_energy / 3.0))
        
        # Calculate weighted total score (CUSTOMIZATION POINT: adjust weights)
        weights = {
            "band_gap_score": 3.0,
            "stability_score": 2.5,
            "formation_energy_score": 1.5
        }
        
        total_score = sum(scores[k] * weights[k] for k in scores.keys())
        max_score = sum(weights.values())
        normalized_score = total_score / max_score
        
        # Apply confidence weighting
        confidence = props.get("confidence", 1.0)
        final_score = normalized_score * confidence
        
        scores["total_score"] = normalized_score
        scores["confidence_weighted_score"] = final_score
        
        candidate["screening_result"]["scores"] = scores
        logger.info(f"  {candidate['id']}: Score = {final_score:.3f}")
    
    def rank_candidates(self):
        """
        Phase 4: Rank passed candidates by score.
        
        CUSTOMIZATION POINT: Modify ranking tiers for your application.
        """
        passed = [c for c in self.results["candidates"] if c["screening_result"]["passed"]]
        
        # Sort by confidence-weighted score
        passed.sort(key=lambda c: c["screening_result"]["scores"]["confidence_weighted_score"], reverse=True)
        
        # Assign ranks
        for rank, candidate in enumerate(passed, start=1):
            candidate["screening_result"]["rank"] = rank
            
            # Add recommendation tier (CUSTOMIZATION POINT)
            score = candidate["screening_result"]["scores"]["confidence_weighted_score"]
            energy_above_hull = candidate["properties"].get("energy_above_hull")
            
            if energy_above_hull is not None and energy_above_hull < 0.1 and score > 0.7:
                tier = "TOP-TIER: Recommend for immediate synthesis"
            elif score > 0.6 or candidate["properties"].get("requires_dft_verification"):
                tier = "SECOND-TIER: Recommend DFT verification"
            else:
                tier = "THIRD-TIER: Exploratory"
            
            candidate["screening_result"]["recommendation_tier"] = tier
        
        self.results["summary_statistics"]["ranked"] = len(passed)
        logger.info(f"Ranked {len(passed)} candidates")
    
    async def process_candidate(self, candidate: Dict) -> bool:
        """Process single candidate through all phases."""
        # Skip if already processed
        if candidate["status"] != "pending":
            logger.info(f"{candidate['id']}: Already processed, skipping")
            return True

        logger.info(f"{candidate['id']}: Processing...")

        try:
            # Phase 1: Validation
            if not await self.validate_structure(candidate):
                return False

            # Phase 2: Property retrieval
            if not await self.retrieve_properties_hierarchical(candidate):
                return False

            # Phase 3: Screening
            if self.apply_screening_criteria(candidate):
                # Phase 4: Calculate scores for passed candidates
                self.calculate_scores(candidate)

            return True

        except Exception as e:
            candidate["status"] = "properties_failed"
            candidate["screening_result"]["rejection_reason"] = f"Processing error: {str(e)}"
            logger.error(f"{candidate['id']}: Processing error - {e}")
            return False

    async def run(self):
        """Execute complete screening workflow."""
        import time
        start_time = time.time()

        logger.info("=" * 80)
        logger.info("STARTING BATCH SCREENING WORKFLOW")
        logger.info("=" * 80)

        # Load candidates (from checkpoint or fresh)
        checkpoint = self.load_checkpoint()
        if checkpoint:
            self.results["candidates"] = checkpoint
        else:
            candidates = self.load_candidates()
            self.results["candidates"] = candidates

        # Process each candidate
        total = len(self.results["candidates"])
        for i, candidate in enumerate(self.results["candidates"], 1):
            logger.info(f"\n[{i}/{total}] Processing {candidate['id']}...")

            await self.process_candidate(candidate)

            # Save checkpoint after each candidate
            self.save_checkpoint()

        # Final ranking
        self.rank_candidates()

        # Record total time
        self.results["metadata"]["screening_time_seconds"] = time.time() - start_time

        # Save final results
        self.save_checkpoint()

        logger.info(f"\nScreening complete in {self.results['metadata']['screening_time_seconds']:.1f} seconds")
        logger.info(f"Results saved to {self.results_file}")


# ============================================================================
# Main Entry Point
# ============================================================================

async def main():
    """Main async entry point."""
    parser = argparse.ArgumentParser(description="Batch screening with hierarchical property retrieval")
    parser.add_argument("--candidates-dir", type=Path, default=Path("candidate-structures"),
                       help="Directory containing candidate CIF files")
    parser.add_argument("--output", type=Path, default=Path("screening_results.json"),
                       help="Output JSON file for results")
    parser.add_argument("--ase-db", type=Path, default=None,
                       help="Optional ASE database path for cached properties")
    
    args = parser.parse_args()
    
    # Create screener
    screener = BatchScreener(
        candidates_dir=args.candidates_dir,
        results_file=args.output,
        ase_db_path=args.ase_db
    )
    
    # Run screening workflow
    await screener.run()


if __name__ == "__main__":
    asyncio.run(main())
